config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
  get '/contact', to: 'home#contact'
  resources :users, only: [:index, :show, :update] do 
    member do
      scope constraints: { format: /(html|js)/ } do
        post 'follow'
        delete 'unfollow'
      end
      scope constraints: { format: :json } do
        get 'following'
        get 'followers'
        get 'tuits'
      end
    end
  end
  resources :tuits, only: [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :user_tuits, on: [:index]

  def index
    render :timeline if user_signed_in?
  end
 
  # No data to pass to the view, so there's no need to define the method
  # def contact
  # end

  private

  def user_tuits
    @tuits = user_signed_in? ? current_user.timeline_tuits : []
  end
  
end

app/views/home/contact.html.erb
<div class="name">
  <h2>Name</h2> 
  José Luis de Vega Andrés
</div>
<div class="email">
  <h2>Email</h2>
  <%=  mail_to 'joseluis.devega@gmail.com' %>
</div>

app/views/home/index.html.erb
<h1>A Bootstrap Starter Template</h1>
<ul class="list-unstyled">
  <li>Bootstrap v3.3.6</li>
  <li>jQuery v1.11.1</li>
</ul>

app/views/home/timeline.html.erb
<!-- timeline.html.erb -->
<div role="main" class="timeline" id="timeline">
  <div class="tuit-box">
    <div class="profile"><%= avatar_url(current_user) %></div> 
    <%= form_for(Tuit.new, url: tuits_url) do |f| %>
      <div class="field">
        <%= f.text_area :text, autofocus: true, maxlength: 160, class: 'countable' %>
        <div class="counter"></div>
      </div>
      <div class="actions">
        <%= f.submit "Tuit" %>
      </div>
    <% end %>
  </div>
  <% cache cache_key_for_relation('timeline/tuits', @tuits) do %>
    <div class="stream-container">
      <%= render @tuits %>    
    </div>
  <% end %>
</div>