config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'
  get '/contact', to: 'home#contact'
  resources :users, only: [:index, :show, :update] do 
    member do
      scope constraints: { format: /(html|js)/ } do
        post 'follow'
        delete 'unfollow'
      end
      scope constraints: { format: :json } do
        get 'following'
        get 'followers'
        get 'tuits'
      end
    end
  end
  resources :tuits, only: [:create]
end

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
  <div class="alert <%= notice ? "alert-info" : "" %><%= alert ? "alert-danger" : "" %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <div >
      <% if notice %>
        <%= notice %>
      <% elsif alert %>
        <%= alert %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Tuiter</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Users', users_path %>
        </li>
        <li>
          <a href="/contact">Contact</a>
        </li>
        <% if user_signed_in? %>
          <li>
            
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <div class="name"><%= current_user.name %></div>
              <%= avatar_url(current_user, tooltip: false) %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to user_url(current_user) do %>
                  <i class="fa fa-fw fa-user"></i> Profile
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to destroy_user_session_url, method: 'delete' do %>
                  <i class="fa fa-fw fa-power-off"></i> Log Out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              Sign in
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <title>Tuiter</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap Social -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.12.0/bootstrap-social.css" rel="stylesheet">


    <!-- Custom CSS -->
    <style>
    body {
      padding-top: 70px;
      /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <%= render partial: 'layouts/alerts' %>

    <%= render partial: 'layouts/menu' %>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <%= yield %>
        </div>
      </div>
    </div>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  </body>
</html>